### ISSUE TITLE
SnarkyJS error when proving claim

### ISSUE THREAD

**Issue by 45930** [qcomps/canvas-zk-app#4]
```
  #ClaimList1

  export class ClaimList1 extends CircuitValue {
    @matrixProp(Field, 1, 2) claims: Field[][];
  
    constructor(claims: ClaimListType) {
      super();
      if (claims.length !== 1) {
        throw Error('ClaimsList1 must have exctly 1 elements');
      }
      this.claims = claims.map((claim) => {
        if (claim) {
          return [Field(claim.i), Field(claim.j)];
        } else {
          return [Field(31), Field(31)];
        }
      });
    }
  }
```

```
  #claimCells

  @method
  claimCells(canvasData: CanvasData, claimList: ClaimList1, pkey: PrivateKey) {
    this.assertValidCanvas(canvasData);
    const mutatedCanvas = canvasData.copy();
    const pubKey = PublicKey.fromPrivateKey(pkey);
    // assert user has fewer than x claims already #TODO
    for (let i = 0; i < CanvasData.size; i++) {
      for (let j = 0; j < CanvasData.size; j++) {
        console.log(i, j)
        claimList.claims.forEach((claim) => {
          const cell = mutatedCanvas.value[i][j];
          const newOwner = Circuit.if(
            Bool.and(
              Field(i).equals(claim[0]),
              Field(j).equals(claim[1])
            ),
            pubKey,
            cell.owner
          )
          mutatedCanvas.updateCellOwner(i, j, newOwner);
        });
      }
    }
    this.canvasHash.set(mutatedCanvas.hash());
  }
```

When I attempt to prove this transaction, I get the following trace:

```
Error: ClaimList1.ofFields: Expected 1 field elements, got 0
    at Function.ofFields (file:///Users/me/Projects/zk-beta/canvas/node_modules/snarkyjs/dist/node/lib/circuit_value.js:87:19)
    at of_array (/Users/me/Projects/zk-beta/canvas/node_modules/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:420768:40)
    at /Users/me/Projects/zk-beta/canvas/node_modules/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:420791:59
    at caml_call1 (/Users/me/Projects/zk-beta/canvas/node_modules/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7610:28)
    at _qb4_ (/Users/me/Projects/zk-beta/canvas/node_modules/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:137193:38)
    at caml_call1 (/Users/me/Projects/zk-beta/canvas/node_modules/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7610:28)
    at exists (/Users/me/Projects/zk-beta/canvas/node_modules/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:141840:38)
    at caml_call3 (/Users/me/Projects/zk-beta/canvas/node_modules/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7614:28)
    at /Users/me/Projects/zk-beta/canvas/node_modules/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:142157:70
    at caml_call1 (/Users/me/Projects/zk-beta/canvas/node_modules/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7610:28)
```

**Comment by 45930** [comment]
Explore full code at 79911b57bbfb88a91069cae6f15a30f81959c316

**Comment by 45930** [comment]
The problem was I initialized the array with `Array<MyType>(1)` which creates an array of length 1, but with values that can't be mapped over (not even `null`).  The fix is to replace with `[new MyType()]` and for longer arrays with fewer than the maximum number of values, pad with `.fill()`.
